version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '127.0.0.1:27017:27017'
    volumes:
      - mongodbdata:/data/db


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '127.0.0.1:5672:5672'
      - '127.0.0.1:15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

